name: 'Trigger Platform workflow'
description: 'Trigger a CloudBees platform workflow from a GHA workflow run.'

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: false
    default: "https://api.cloudbees.io"
  cloudbees-pat:
    description: 'The CloudBees platform personal access token.'
    required: true
  component-id:
    description: 'The Component-id of the CloudBees workflow to be run. '
    required: false
  branch-name:
    description: 'The branch name of the CloudBees workflow to be run.'
    required: false
  workflow-file-name:
    description: 'The name of the CloudBees workflow to be run.'
    required: true
  workflow-inputs:
    description: 'Input parameters required to run the workflow, formatted as JSON data in key/value pairs.'
    required: false

outputs:
  cbp_run_url:
    description: "The triggered cbp run url"

runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-run-cbp-workflow:main-8f2add6498938993dd9fd9b95dd91c4df42862e2"
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    CLOUDBEES_API_TOKEN: ${{ inputs.cloudbees-pat }}
    COMPONENT_ID: ${{ inputs.component-id }}
    BRANCH_NAME: ${{ inputs.branch-name }}
    WORKFLOW_FILE_NAME: ${{ inputs.workflow-file-name }}
    WORKFLOW_INPUTS: ${{ inputs.workflow-inputs }}
