= Run Workflow
 
Use this action to run CloudBees workflow from GitHub Actions workflow

== Inputs
 
[cols="2a,1a,1a,3a",options="header"]
.Input details
|===
 
| Input name
| Data type
| Required
| Description
 
| `cloudbees-url`
| String
| No
| The CloudBees platform URL. Default value is `"https://api.cloudbees.io"`.
 
| `cloudbees-pat`
| String
| Yes
| The CloudBees platform personal access token.
 
| `component-id`
| String
| No
| The Component-id of the CloudBees workflow to be run.
 
| `branch-name`
| String
| No
| The branch of the CloudBees workflow to be run.

| `workflow-file-name`
| String
| Yes
| The name of the CloudBees workflow to be run.

| `workflow-inputs`
| JSON string
| No
| Input parameters required to run the workflow, formatted as JSON data in key/value pairs.
 
|===

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `cloudbees-url`
| String
| No
| The CloudBees platform URL. Default value is `"https://api.cloudbees.io"`.

|===


== Usage example
 
In your YAML file, add:
 
[source,yaml]
----
    - name: Run Workflow
      uses: cloudbees-gha-cbp/run-workflow@v1
      with:
        cloudbees-pat: ${{ secrets.MY_PAT }}
        component-id: "0a93f2dc-ae5c-4246-ab82-3db8c8328284"
        branch-name: "main"
        workflow-file-name: "workflow.yaml"
        workflow-inputs: '{"workflowInput1": "test1"}'
 
----

Using output

The platform workflow file below prints the cbp-run-url captured as output from action:

[source,yaml]
----
    - name: Run Workflow
      uses: cloudbees-gha-cbp/run-workflow@v1
      id: run-workflow-action
      with:
        cloudbees-pat: ${{ secrets.MY_PAT }}
        component-id: "0a93f2dc-ae5c-4246-ab82-3db8c8328284"
        branch-name: "main"
        workflow-file-name: "workflow.yaml"
        workflow-inputs: '{"workflowInput1": "test1"}'

    - name: Print runUrl output
      run: echo "The CloudBees run URL is ${{ steps.run-workflow-action.outputs.cbp_run_url}}"

----

== License
 
This code is made available under the
link:https://opensource.org/license/mit/[MIT license].
 
== References
 
* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].